#define THRUSTER_SPEED_REGISTERS 0
#define AVIONICS_REGISTERS 6
#define MANIPULATOR_REGISTERS 10
#define RELAY_REGISTER 14
#define VOLTMETER_REGISTER 15
#define THRUSTER_RPM_REGISTERS 16
#define THRUSTER_TEMP_REGISTERS 22
#define COMMUNICATION_REGISTER 28
